const reportCards2024 = [
    // Nursery Students
        {studentName: "ABDUL MALIK MUHAMMAD",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "2",
            "colouring": "3",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "GOOD",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "GOOD"},
        aggregate: "",
        position: "15th"},

        {studentName: "ABDUL MUMIN ABDUBAKAR",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "2",
            "numeracy": "1",
            "writing": "1",
            "arabic": "2",
            "colouring": "3",
            "creative arts": "1"},
  remarks: {"language & literacy": "VERY GOOD",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "11th"},

        {studentName: "ABDUL MUMIN ISMAIL",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "2",
            "colouring": "4",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "GOOD",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "GOOD"},
        aggregate: "",
        position: "16th"},

        {studentName: "BUADU ANDOH FADILA",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "3",
            "creative arts": "1"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "GOOD",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "9th"},

        {studentName: "FAISAL IDDRISS",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
  grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "4",
            "creative arts": "1"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "GOOD",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "6th"},

        {studentName: "FATIMA ABU ADAMS",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "1",
            "creative arts": "1"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "EXCELLENT",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "3rd"},

        {studentName: "FATIMA EFFAH",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "2",
            "creative arts": "1"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "VERY GOOD",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "5th"},

        {studentName: "FATIMA",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "1",
            "creative arts": "1"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "EXCELLENT",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "7th"},

        {studentName: "FALILAH ANAS",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "1",
            "creative arts": "1"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "EXCELLENT",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "1st"},

        {studentName: "HAWAWU ABDUL KADRI",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "1",
            "creative arts": "1"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "EXCELLENT",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "2nd"},

        {studentName: "HIKMATU MUSTAPHA",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "4",
            "numeracy": "4",
            "writing": "4",
            "arabic": "5",
            "colouring": "2",
            "creative arts": "3"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "GOOD",
            "writing": "GOOD",
            "arabic": "CREDIT",
            "colouring": "VERY GOOD",
            "creative arts": "GOOD"},
        aggregate: "",
        position: "17th"},

        {studentName: "MOHAMMAD A. OMALITI",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "1",
            "creative arts": "1"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "EXCELLENT",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "8th"},

        {studentName: "MUHAMMAD SULAIMAN",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "2",
            "numeracy": "1",
            "writing": "3",
            "arabic": "3",
            "colouring": "4",
            "creative arts": "2"},
  remarks: {"language & literacy": "VERY GOOD",
            "numeracy": "EXCELLENT",
            "writing": "GOOD",
            "arabic": "GOOD",
            "colouring": "GOOD",
            "creative arts": "VERY GOOD"},
        aggregate: "",
        position: "14th"},

        {studentName: "SAANI ADANAN",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "1",
            "creative arts": "1"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "EXCELLENT",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "10th"},

        {studentName: "SAUDA ISMAIL",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "2",
            "numeracy": "1",
            "writing": "2",
            "arabic": "1",
            "colouring": "5",
            "creative arts": "1"},
  remarks: {"language & literacy": "VERY GOOD",
            "numeracy": "EXCELLENT",
            "writing": "VERY GOOD",
            "arabic": "EXCELLENT",
            "colouring": "CREDIT",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "13th"},

        {studentName: "SHABIWU",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "3",
            "creative arts": "1"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "GOOD",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "4th"},

        {studentName: "SHAMIMA MUHAMMAD",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "4",
            "creative arts": "2"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "GOOD",
            "creative arts": "VERY GOOD"},
        aggregate: "",
        position: "12th"},
    // Add more nursery students...

    // KG1 Students
    {studentName: "HANIF  ABDUL AZIZ",
        class: "KG 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "1",
            "creative arts": "1"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "EXCELLENT",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "2nd"},

  {studentName: "HANNATU IBRAHIM",
        class: "KG 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "3",
            "writing": "3",
            "arabic": "1",
            "colouring": "2",
            "creative arts": "2"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "GOOD",
            "writing": "GOOD",
            "arabic": "EXCELLENT",
            "colouring": "VERY GOOD",
            "creative arts": "VERY GOOD"},
        aggregate: "",
        position: "5th"},

  {studentName: "IMRANATU IBRAHIM",
        class: "KG 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "2",
            "numeracy": "1",
            "writing": "3",
            "arabic": "1",
            "colouring": "3",
            "creative arts": "1"},
  remarks: {"language & literacy": "VERY GOOD",
            "numeracy": "EXCELLENT",
            "writing": "GOOD",
            "arabic": "EXCELLENT",
            "colouring": "GOOD",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "5th"},

  {studentName: "MOHAMMAD ABUBAKAR",
        class: "KG 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "1",
            "creative arts": "1"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "EXCELLENT",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "1st"},

  {studentName: "MUSTAQIM DAUD",
        class: "KG 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "4",
            "writing": "4",
            "arabic": "1",
            "colouring": "4",
            "creative arts": "3"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "GOOD",
            "writing": "GOOD",
            "arabic": "EXCELLENT",
            "colouring": "GOOD",
            "creative arts": "GOOD"},
        aggregate: "",
        position: "7th"},

  {studentName: "NAZIRU MUSAH",
        class: "KG 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "2",
            "arabic": "1",
            "colouring": "4",
            "creative arts": "3"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "VERY GOOD",
            "arabic": "EXCELLENT",
            "colouring": "GOOD",
            "creative arts": "GOOD"},
        aggregate: "",
        position: "4th"},

  {studentName: "NIHAAD ABDUL MALIK",
        class: "KG 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "2",
            "creative arts": "1"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "VERY GOOD",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "5th"},

  {studentName: "SUWAIBA ALHASSAN",
        class: "KG 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "1",
            "colouring": "4",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "GOOD",
            "arabic": "EXCELLENT",
            "colouring": "GOOD",
            "creative arts": "GOOD"},
        aggregate: "",
        position: "8th"},
    // Add more KG 1 students...

    // Basic 1 Students
       {studentName: "ABDUL-RAUF IDDRISS",
        class: "Basic 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "2",
            "history": "3",
            "mathematics": "1",
            "science": "1",
            "arabic": "2",
            "mfantse": "2",
            "religious & moral education": "1"},
  remarks: {"english language": "VERY GOOD",
            "history": "GOOD",
            "mathematics": "EXCELLENT",
            "science": "EXCELLENT",
            "arabic": "VERY GOOD",
            "mfantse": "VERY GOOD",
            "religious & moral education": "EXCELLENT"},
        aggregate: "",
        position: "3rd"},

        {studentName: "ABEKA YAKUB",
        class: "Basic 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "7",
            "history": "9",
            "mathematics": "8",
            "science": "4",
            "arabic": "9",
            "mfantse": "7",
            "religious & moral education": "9"},
  remarks: {"english language": "PASS",
            "history": "FAIL",
            "mathematics": "PASS",
            "science": "GOOD",
            "arabic": "FAIL",
            "mfantse": "PASS",
            "religious & moral education": "FAIL"},
        aggregate: "",
        position: "11th"},

        {studentName: "AISHATU DAUD",
        class: "Basic 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "1",
            "history": "1",
            "mathematics": "1",
            "science": "1",
            "arabic": "1",
            "mfantse": "1",
            "religious & moral education": "1"},
  remarks: {"english language": "EXCELLENT",
            "history": "EXCELLENT",
            "mathematics": "EXCELLENT",
            "science": "EXCELLENT",
            "arabic": "EXCELLENT",
            "mfantse": "EXCELLENT",
            "religious & moral education": "EXCELLENT"},
        aggregate: "",
        position: "1st"},

        {studentName: "BUHARI SHAIBU",
        class: "Basic 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "4",
            "history": "8",
            "mathematics": "4",
            "science": "1",
            "arabic": "4",
            "mfantse": "9",
            "religious & moral education": "9"},
  remarks: {"english language": "GOOD",
            "history": "PASS",
            "mathematics": "GOOD",
            "science": "EXCELLENT",
            "arabic": "GOOD",
            "mfantse": "FAIL",
            "religious & moral education": "FAIL"},
        aggregate: "",
        position: "8th"},

        {studentName: "HAMZA EFFAH",
        class: "Basic 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "4",
            "history": "8",
            "mathematics": "6",
            "science": "4",
            "arabic": "4",
            "mfantse": "6",
            "religious & moral education": "9"},
  remarks: {"english language": "GOOD",
            "history": "PASS",
            "mathematics": "CREDIT",
            "science": "GOOD",
            "arabic": "GOOD",
            "mfantse": "CREDIT",
            "religious & moral education": "FAIL"},
        aggregate: "",
        position: "10th"},

        {studentName: "ISMAIL MOHAMMAD",
        class: "Basic 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "4",
            "history": "9",
            "mathematics": "6",
            "science": "5",
            "arabic": "1",
            "mfantse": "7",
            "religious & moral education": "9"},
  remarks: {"english language": "GOOD",
            "history": "FAIL",
            "mathematics": "CREDIT",
            "science": "CREDIT",
            "arabic": "EXCELLENT",
            "mfantse": "PASS",
            "religious & moral education": "FAIL"},
        aggregate: "",
        position: "9th"},

        {studentName: "MARYAM ANASS",
        class: "Basic 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "2",
            "history": "1",
            "mathematics": "4",
            "science": "2",
            "arabic": "1",
            "mfantse": "4",
            "religious & moral education": "9"},
  remarks: {"english language": "VERY GOOD",
            "history": "EXCELLENT",
            "mathematics": "GOOD",
            "science": "VERY GOOD",
            "arabic": "EXCELLENT",
            "mfantse": "GOOD",
            "religious & moral education": "FAIL"},
        aggregate: "",
        position: "5th"},

        {studentName: "DAZIE MUBARAK ISMAIL",
        class: "Basic 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "1",
            "history": "3",
            "mathematics": "4",
            "science": "1",
            "arabic": "9",
            "mfantse": "2",
            "religious & moral education": "5"},
  remarks: {"english language": "EXCELLENT",
            "history": "GOOD",
            "mathematics": "GOOD",
            "science": "EXCELLENT",
            "arabic": "FAIL",
            "mfantse": "VERY GOOD",
            "religious & moral education": "CREDIT"},
        aggregate: "",
        position: "7th"},

        {studentName: "RAHINA ABUBAKAR",
        class: "Basic 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "1",
            "history": "1",
            "mathematics": "3",
            "science": "1",
            "arabic": "1",
            "mfantse": "1",
            "religious & moral education": "1"},
  remarks: {"english language": "EXCELLENT",
            "history": "EXCELLENT",
            "mathematics": "GOOD",
            "science": "EXCELLENT",
            "arabic": "EXCELLENT",
            "mfantse": "EXCELLENT",
            "religious & moral education": "EXCELLENT"},
        aggregate: "",
        position: "2nd"},

        {studentName: "SALMAN MUSAH",
        class: "Basic 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "2",
            "history": "5",
            "mathematics": "3",
            "science": "3",
            "arabic": "2",
            "mfantse": "5",
            "religious & moral education": "7"},
  remarks: {"english language": "VERY GOOD",
            "history": "CREDIT",
            "mathematics": "GOOD",
            "science": "GOOD",
            "arabic": "VERY GOOD",
            "mfantse": "CREDIT",
            "religious & moral education": "PASS"},
        aggregate: "",
        position: "6th"},

        {studentName: "YUSSIF MOHAMMAD",
        class: "Basic 1",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "3",
            "history": "5",
            "mathematics": "1",
            "science": "2",
            "arabic": "1",
            "mfantse": "4",
            "religious & moral education": "3"},
  remarks: {"english language": "GOOD",
            "history": "CREDIT",
            "mathematics": "EXCELLENT",
            "science": "VERY GOOD",
            "arabic": "EXCELLENT",
            "mfantse": "GOOD",
            "religious & moral education": "GOOD"},
        aggregate: "",
        position: "4th"},
    // Add more Basic 1 students...

    // Basic 2 Students
    {studentName: "ABDUL AZIZ LABIB",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "1",
            "history": "2",
            "mathematics": "1",
            "science": "1",
            "arabic": "1",
            "creative arts": "1",
            "mfantse": "1",
            "religious & moral education": "1"},
  remarks: {"english language": "EXCELLENT",
            "history": "VERY GOOD",
            "mathematics": "EXCELLENT",
            "science": "EXCELLENT",
            "arabic": "EXCELLENT",
            "creative arts": "EXCELLENT",
            "mfantse": "EXCELLENT",
            "religious & moral education": "EXCELLENT"},
        aggregate: "",
        position: "2nd"},

        {studentName: "MOHAMMAD ABDUL RAHMAN",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "1",
            "history": "1",
            "mathematics": "1",
            "science": "1",
            "arabic": "1",
            "creative arts": "1",
            "mfantse": "1",
            "religious & moral education": "1"},
  remarks: {"english language": "EXCELLENT",
            "history": "EXCELLENT",
            "mathematics": "EXCELLENT",
            "science": "EXCELLENT",
            "arabic": "EXCELLENT",
            "creative arts": "EXCELLENT",
            "mfantse": "EXCELLENT",
            "religious & moral education": "EXCELLENT"},
        aggregate: "",
        position: "5th"},

        {studentName: "IBRAHIM ABDUL RASHIID",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "3",
            "history": "6",
            "mathematics": "2",
            "science": "3",
            "arabic": "1",
            "creative arts": "1",
            "mfantse": "4",
            "religious & moral education": "5"},
  remarks: {"english language": "GOOD",
            "history": "CREDIT",
            "mathematics": "VERY GOOD",
            "science": "GOOD",
            "arabic": "EXCELLENT",
            "creative arts": "EXCELLENT",
            "mfantse": "GOOD",
            "religious & moral education": "CREDIT"},
        aggregate: "",
        position: "13th"},

        {studentName: "ADU BRESI BLESSED",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "1",
            "history": "3",
            "mathematics": "4",
            "science": "3",
            "arabic": "1",
            "creative arts": "1",
            "mfantse": "1",
            "religious & moral education": "2"},
  remarks: {"english language": "EXCELLENT",
            "history": "GOOD",
            "mathematics": "GOOD",
            "science": "GOOD",
            "arabic": "EXCELLENT",
            "creative arts": "EXCELLENT",
            "mfantse": "EXCELLENT",
            "religious & moral education": "VERY GOOD"},
        aggregate: "",
        position: "9th"},

        {studentName: "AL-HASSAN HAMZA",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "4",
            "history": "5",
            "mathematics": "1",
            "science": "4",
            "arabic": "1",
            "creative arts": "2",
            "mfantse": "4",
            "religious & moral education": "2"},
  remarks: {"english language": "GOOD",
            "history": "CREDIT",
            "mathematics": "EXCELLENT",
            "science": "GOOD",
            "arabic": "EXCELLENT",
            "creative arts": "VERY GOOD",
            "mfantse": "GOOD",
            "religious & moral education": "VERY GOOD"},
        aggregate: "",
        position: "12th"},

        {studentName: "ALHASSAN IMRAN",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "2",
            "history": "1",
            "mathematics": "1",
            "science": "1",
            "arabic": "1",
            "creative arts": "1",
            "mfantse": "1",
            "religious & moral education": "1"},
  remarks: {"english language": "VERY GOOD",
            "history": "EXCELLENT",
            "mathematics": "EXCELLENT",
            "science": "EXCELLENT",
            "arabic": "EXCELLENT",
            "creative arts": "EXCELLENT",
            "mfantse": "EXCELLENT",
            "religious & moral education": "EXCELLENT"},
        aggregate: "",
        position: "3rd"},

        {studentName: "ALHASSAN UMAR IDDRISS",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "1",
            "history": "1",
            "mathematics": "1",
            "science": "1",
            "arabic": "1",
            "creative arts": "1",
            "mfantse": "1",
            "religious & moral education": "1"},
  remarks: {"english language": "EXCELLENT",
            "history": "EXCELLENT",
            "mathematics": "EXCELLENT",
            "science": "EXCELLENT",
            "arabic": "EXCELLENT",
            "creative arts": "EXCELLENT",
            "mfantse": "EXCELLENT",
            "religious & moral education": "EXCELLENT"},
        aggregate: "",
        position: "1st"},

        {studentName: "AMOAH RAHIMA",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "4",
            "history": "5",
            "mathematics": "1",
            "science": "3",
            "arabic": "1",
            "creative arts": "1",
            "mfantse": "1",
            "religious & moral education": "4"},
  remarks: {"english language": "GOOD",
            "history": "CREDIT",
            "mathematics": "EXCELLENT",
            "science": "GOOD",
            "arabic": "EXCELLENT",
            "creative arts": "EXCELLENT",
            "mfantse": "EXCELLENT",
            "religious & moral education": "GOOD"},
        aggregate: "",
        position: "10th"},

        {studentName: "ANNIFUL HAWA",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "2",
            "history": "3",
            "mathematics": "1",
            "science": "1",
            "arabic": "2",
            "creative arts": "5",
            "mfantse": "2",
            "religious & moral education": "1"},
  remarks: {"english language": "VERY GOOD",
            "history": "GOOD",
            "mathematics": "EXCELLENT",
            "science": "EXCELLENT",
            "arabic": "VERY GOOD",
            "creative arts": "CREDIT",
            "mfantse": "VERY GOOD",
            "religious & moral education": "EXCELLENT"},
        aggregate: "",
        position: "8th"},

        {studentName: "MOHAMMAD HAWA",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "1",
            "history": "3",
            "mathematics": "1",
            "science": "1",
            "arabic": "1",
            "creative arts": "1",
            "mfantse": "2",
            "religious & moral education": "2"},
  remarks: {"english language": "EXCELLENT",
            "history": "GOOD",
            "mathematics": "EXCELLENT",
            "science": "EXCELLENT",
            "arabic": "EXCELLENT",
            "creative arts": "EXCELLENT",
            "mfantse": "VERY GOOD",
            "religious & moral education": "VERY GOOD"},
        aggregate: "",
        position: "7th"},

        {studentName: "MOHAMMAD KHALID",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "4",
            "history": "4",
            "mathematics": "3",
            "science": "4",
            "arabic": "1",
            "creative arts": "3",
            "mfantse": "1",
            "religious & moral education": "4"},
  remarks: {"english language": "GOOD",
            "history": "GOOD",
            "mathematics": "GOOD",
            "science": "GOOD",
            "arabic": "EXCELLENT",
            "creative arts": "GOOD",
            "mfantse": "EXCELLENT",
            "religious & moral education": "GOOD"},
        aggregate: "",
        position: "14th"},

        {studentName: "NURUEEN RAHMA",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "4",
            "history": "5",
            "mathematics": "4",
            "science": "5",
            "arabic": "1",
            "creative arts": "3",
            "mfantse": "2",
            "religious & moral education": "4"},
  remarks: {"english language": "GOOD",
            "history": "CREDIT",
            "mathematics": "GOOD",
            "science": "CREDIT",
            "arabic": "EXCELLENT",
            "creative arts": "GOOD",
            "mfantse": "VERY GOOD",
            "religious & moral education": "GOOD"},
        aggregate: "",
        position: "15th"},

        {studentName: "OMALIJA ALI AKMEY-ALHASSAN",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "1",
            "history": "1",
            "mathematics": "1",
            "science": "1",
            "arabic": "1",
            "creative arts": "1",
            "mfantse": "1",
            "religious & moral education": "1"},
  remarks: {"english language": "EXCELLENT",
            "history": "EXCELLENT",
            "mathematics": "EXCELLENT",
            "science": "EXCELLENT",
            "arabic": "EXCELLENT",
            "creative arts": "EXCELLENT",
            "mfantse": "EXCELLENT",
            "religious & moral education": "EXCELLENT"},
        aggregate: "",
        position: "4th"},

        {studentName: "SULAIMAN SHAMIMA TIPAGYA",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "4",
            "history": "5",
            "mathematics": "3",
            "science": "5",
            "arabic": "1",
            "creative arts": "1",
            "mfantse": "1",
            "religious & moral education": "4"},
  remarks: {"english language": "GOOD",
            "history": "CREDIT",
            "mathematics": "GOOD",
            "science": "CREDIT",
            "arabic": "EXCELLENT",
            "creative arts": "EXCELLENT",
            "mfantse": "EXCELLENT",
            "religious & moral education": "GOOD"},
        aggregate: "",
        position: "11th"},

        {studentName: "ABDUL GANIU ABDUL GAFAR",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "2",
            "history": "3",
            "mathematics": "1",
            "science": "1",
            "arabic": "5",
            "creative arts": "5",
            "mfantse": "2",
            "religious & moral education": "1"},
  remarks: {"english language": "VERY GOOD",
            "history": "GOOD",
            "mathematics": "EXCELLENT",
            "science": "EXCELLENT",
            "arabic": "CREDIT",
            "creative arts": "CREDIT",
            "mfantse": "VERY GOOD",
            "religious & moral education": "EXCELLENT"},
        aggregate: "",
        position: "6th"},

        {studentName: "YAMOAH AGARTHA",
        class: "Basic 2",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "5",
            "history": "8",
            "mathematics": "5",
            "science": "7",
            "arabic": "1",
            "creative arts": "5",
            "mfantse": "8",
            "religious & moral education": "5"},
  remarks: {"english language": "CREDIT",
            "history": "PASS",
            "mathematics": "CREDIT",
            "science": "PASS",
            "arabic": "EXCELLENT",
            "creative arts": "CREDIT",
            "mfantse": "PASS",
            "religious & moral education": "CREDIT"},
        aggregate: "",
        position: "16th"},
    // Add more Basic 2 students...

    // Class 4 Students
       {studentName: "SEID IDDRISS UTHMAN",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "5",
            "history": "6",
            "mathematics": "4",
            "science": "5",
            "arabic": "1",
            "computing": "5",
            "creative arts": "5",
            "mfantse": "5",
            "religious & moral education": "4"},
  remarks: {"english language": "CREDIT",
            "history": "CREDIT",
            "mathematics": "GOOD",
            "science": "CREDIT",
            "arabic": "EXCELLENT",
            "computing": "CREDIT",
            "creative arts": "CREDIT",
            "mfantse": "CREDIT",
            "religious & moral education": "GOOD"},
    aggregate: "",
    position: "7th"},
       
       {studentName: "MASUD AL-HASSAN",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "9",
            "history": "8",
            "mathematics": "8",
            "science": "4",
            "arabic": "1",
            "computing": "8",
            "creative arts": "4",
            "mfantse": "4",
            "religious & moral education": "4"},
  remarks: {"english language": "FAIL",
            "history": "PASS",
            "mathematics": "PASS",
            "science": "GOOD",
            "arabic": "EXCELLENT",
            "computing": "PASS",
            "creative arts": "GOOD",
            "mfantse": "GOOD",
            "religious & moral education": "GOOD"},
        aggregate: "",
        position: "9th"},

        {studentName: "ABDUL MAJID DONKOH",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "5",
            "history": "6",
            "mathematics": "6",
            "science": "4",
            "arabic": "1",
            "computing": "8",
            "creative arts": "4",
            "mfantse": "6",
            "religious & moral education": "3"}, 
  remarks: {"english language": "CREDIT",
            "history": "CREDIT",
            "mathematics": "CREDIT",
            "science": "GOOD",
            "arabic": "EXCELLENT",
            "computing": "PASS",
            "creative arts": "GOOD",
            "mfantse": "CREDIT",
            "religious & moral education": "GOOD"},
    aggregate: "",
    position: "8th"},

    {studentName: "FARIDA IBRAHIM",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "2",
            "history": "4",
            "mathematics": "4",
            "science": "2",
            "arabic": "1",
            "computing": "4",
            "creative arts": "4",
            "mfantse": "3",
            "religious & moral education": "4"},
  remarks: {"english language": "VERY GOOD",
            "history": "GOOD",
            "mathematics": "GOOD",
            "science": "VERY GOOD",
            "arabic": "EXCELLENT",
            "computing": "GOOD",
            "creative arts": "GOOD",
            "mfantse": "GOOD",
            "religious & moral education": "GOOD"},
    aggregate: "",
    position: "4th"},

    {studentName: "FATI ADAM",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "9",
            "history": "9",
            "mathematics": "9",
            "science": "8",
            "arabic": "2",
            "computing": "9",
            "creative arts": "8",
            "mfantse": "9",
            "religious & moral education": "8"},
  remarks: {"english language": "FAIL",
            "history": "FAIL",
            "mathematics": "FAIL",
            "science": "PASS",
            "arabic": "VERY GOOD",
            "computing": "FAIL",
            "creative arts": "PASS",
            "mfantse": "FAIL",
            "religious & moral education": "PASS"},
    aggregate: "",
    position: "15th"},

    {studentName: "HASIATU MOHAMMAD",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "3",
            "history": "3",
            "mathematics": "3",
            "science": "4",
            "arabic": "1",
            "computing": "4",
            "creative arts": "2",
            "mfantse": "2",
            "religious & moral education": "2"},
  remarks: {"english language": "GOOD",
            "history": "GOOD",
            "mathematics": "GOOD",
            "science": "GOOD",
            "arabic": "EXCELLENT",
            "computing": "GOOD",
            "creative arts": "VERY GOOD",
            "mfantse": "VERY GOOD",
            "religious & moral education": "VERY GOOD"},
    aggregate: "",
    position: "2nd"},

    {studentName: "SAAHA IBRAHIM",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "9",
            "history": "9",
            "mathematics": "9",
            "science": "7",
            "arabic": "3",
            "computing": "9",
            "creative arts": "7",
            "mfantse": "9",
            "religious & moral education": "6"},  
  remarks: {"english language": "FAIL",
            "history": "FAIL",
            "mathematics": "FAIL",
            "science": "PASS",
            "arabic": "GOOD",
            "computing": "FAIL",
            "creative arts": "PASS",
            "mfantse": "FAIL",
            "religious & moral education": "CREDIT"},
    aggregate: "",
    position: "14th"},

    {studentName: "ABDUL AZIZ LUTUFIA BAKURI",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "3",
            "history": "5",
            "mathematics": "4",
            "science": "4",
            "arabic": "1",
            "computing": "4",
            "creative arts": "4",
            "mfantse": "2",
            "religious & moral education": "1"},  
  remarks: {"english language": "GOOD",
            "history": "CREDIT",
            "mathematics": "GOOD",
            "science": "GOOD",
            "arabic": "EXCELLENT",
            "computing": "GOOD",
            "creative arts": "GOOD",
            "mfantse": "VERY GOOD",
            "religious & moral education": "EXCELLENT"},
    aggregate: "",
    position: "3rd"},

    {studentName: "MESAH MOHAMMAD",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "5",
            "history": "7",
            "mathematics": "9",
            "science": "7",
            "arabic": "1",
            "computing": "8",
            "creative arts": "6",
            "mfantse": "7",
            "religious & moral education": "8"},
  remarks: {"english language": "CREDIT",
            "history": "PASS",
            "mathematics": "FAIL",
            "science": "PASS",
            "arabic": "EXCELLENT",
            "computing": "PASS",
            "creative arts": "CREDIT",
            "mfantse": "PASS",
            "religious & moral education": "PASS"},
    aggregate: "",
    position: "13th"},

    {studentName: "ISMAIL MOHAMMAD",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "6",
            "history": "9",
            "mathematics": "9",
            "science": "7",
            "arabic": "1",
            "computing": "7",
            "creative arts": "7",
            "mfantse": "9",
            "religious & moral education": "6"},
  remarks: {"english language": "CREDIT",
            "history": "FAIL",
            "mathematics": "FAIL",
            "science": "PASS",
            "arabic": "EXCELLENT",
            "computing": "PASS",
            "creative arts": "PASS",
            "mfantse": "FAIL",
            "religious & moral education": "CREDIT"},
    aggregate: "",
    position: "12th"},

    {studentName: "RUKAYATU IBRAHIM",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "9",
            "history": "9",
            "mathematics": "9",
            "science": "8",
            "arabic": "3",
            "computing": "9",
            "creative arts": "8",
            "mfantse": "9",
            "religious & moral education": "8"},
  remarks: {"english language": "FAIL",
            "history": "FAIL",
            "mathematics": "FAIL",
            "science": "PASS",
            "arabic": "GOOD",
            "computing": "FAIL",
            "creative arts": "PASS",
            "mfantse": "FAIL",
            "religious & moral education": "PASS"},
    aggregate: "",
    position: "11th"},

    {studentName: "SAUDATU IBRAHIM",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "5",
            "history": "4",
            "mathematics": "6",
            "science": "5",
            "arabic": "1",
            "computing": "6",
            "creative arts": "5",
            "mfantse": "5",
            "religious & moral education": "5"},
  remarks: {"english language": "CREDIT",
            "history": "GOOD",
            "mathematics": "CREDIT",
            "science": "CREDIT",
            "arabic": "EXCELLENT",
            "computing": "CREDIT",
            "creative arts": "CREDIT",
            "mfantse": "CREDIT",
            "religious & moral education": "CREDIT"},
    aggregate: "",
    position: "10th"},

    {studentName: "SHAMSIATU AHMED",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "1",
            "history": "3",
            "mathematics": "5",
            "science": "1",
            "arabic": "1",
            "computing": "5",
            "creative arts": "4",
            "mfantse": "1",
            "religious & moral education": "1"}, 
  remarks: {"english language": "EXCELLENT",
            "history": "GOOD",
            "mathematics": "CREDIT",
            "science": "EXCELLENT",
            "arabic": "EXCELLENT",
            "computing": "CREDIT",
            "creative arts": "GOOD",
            "mfantse": "EXCELLENT",
            "religious & moral education": "EXCELLENT"},
    aggregate: "",
    position: "1st"},

    {studentName: "ABDUL BAASIT SULLEYMAN",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "4",
            "history": "7",
            "mathematics": "4",
            "science": "4",
            "arabic": "1",
            "computing": "4",
            "creative arts": "4",
            "mfantse": "5",
            "religious & moral education": "3"},
  
  remarks: {"english language": "GOOD",
            "history": "PASS",
            "mathematics": "GOOD",
            "science": "GOOD",
            "arabic": "EXCELLENT",
            "computing": "GOOD",
            "creative arts": "GOOD",
            "mfantse": "CREDIT",
            "religious & moral education": "GOOD"},
    aggregate: "",
    position: "6th"},

    {studentName: "UMMU USMAN",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "3",
            "history": "5",
            "mathematics": "9",
            "science": "1",
            "arabic": "1",
            "computing": "3",
            "creative arts": "4",
            "mfantse": "4",
            "religious & moral education": "2"},
  remarks: {"english language": "GOOD",
            "history": "CREDIT",
            "mathematics": "FAIL",
            "science": "EXCELLENT",
            "arabic": "EXCELLENT",
            "computing": "GOOD",
            "creative arts": "GOOD",
            "mfantse": "GOOD",
            "religious & moral education": "VERY GOOD"},
    aggregate: "",
    position: "5th"},

    {studentName: "ZALIYA SULLEYMAN",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"english language": "9",
            "history": "9",
            "mathematics": "9",
            "science": "9",
            "arabic": "4",
            "computing": "9",
            "creative arts": "9",
            "mfantse": "7",
            "religious & moral education": "9"},
  remarks: {"english language": "FAIL",
            "history": "FAIL",
            "mathematics": "FAIL",
            "science": "FAIL",
            "arabic": "GOOD",
            "computing": "FAIL",
            "creative arts": "FAIL",
            "mfantse": "PASS",
            "religious & moral education": "FAIL"},
    aggregate: "",
    position: "16th"},
    // Add more Class 4 students...

    // Form 1 Students
    {
        studentName: "IBRAHIM HALIMA",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "9",
            "mathematics": "9",
            "science": "9",
            "social studies": "8",
            "arabic": "9",
            "career technology": "9",
            "computing": "6",
            "creative arts": "8",
            "mfantse": "9",
            "religious & moral education": "9"
        },
        remarks: {
            "english language": "FAIL",
            "mathematics": "FAIL",
            "science": "FAIL",
            "social studies": "PASS",
            "arabic": "FAIL",
            "career technology": "FAIL",
            "computing": "CREDIT",
            "creative arts": "PASS",
            "mfantse": "FAIL",
            "religious & moral education": "FAIL"
        },
        aggregate: ""
    },
    {
        studentName: "AHMAD BILIKIS",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "7",
            "mathematics": "9",
            "science": "7",
            "social studies": "4",
            "arabic": "9",
            "career technology": "6",
            "computing": "2",
            "creative arts": "5",
            "mfantse": "9",
            "religious & moral education": "5"
        },
        remarks: {
            "english language": "PASS",
            "mathematics": "FAIL",
            "science": "PASS",
            "social studies": "GOOD",
            "arabic": "FAIL",
            "career technology": "CREDIT",
            "computing": "VERY GOOD",
            "creative arts": "FAIL",
            "mfantse": "FAIL",
            "religious & moral education": "CREDIT"
        },
        aggregate: ""
    },
    {
        studentName: "APPIAH HANIFA",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "8",
            "mathematics": "9",
            "science": "9",
            "social studies": "5",
            "arabic": "9",
            "career technology": "4",
            "computing": "3",
            "creative arts": "4",
            "mfantse": "9",
            "religious & moral education": "4"
        },
        remarks: {
            "english language": "PASS",
            "mathematics": "FAIL",
            "science": "FAIL",
            "social studies": "CREDIT",
            "arabic": "FAIL",
            "career technology": "GOOD",
            "computing": "GOOD",
            "creative arts": "GOOD",
            "mfantse": "FAIL",
            "religious & moral education": "GOOD"
        },
        aggregate: ""
    },
    {
        studentName: "ABDUL MUMIN BASIRA",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "6",
            "mathematics": "9",
            "science": "6",
            "social studies": "1",
            "arabic": "9",
            "career technology": "4",
            "computing": "3",
            "creative arts": "4",
            "mfantse": "9",
            "religious & moral education": "4"
        },
        remarks: {
            "english language": "CREDIT",
            "mathematics": "FAIL",
            "science": "CREDIT",
            "social studies": "EXCELLENT",
            "arabic": "FAIL",
            "career technology": "GOOD",
            "computing": "GOOD",
            "creative arts": "GOOD",
            "mfantse": "FAIL",
            "religious & moral education": "GOOD"
        },
        aggregate: ""
    },
    {
        studentName: "MOHAMMAD IBRAHIM",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "9",
            "mathematics": "9",
            "science": "9",
            "social studies": "7",
            "arabic": "9",
            "career technology": "7",
            "computing": "7",
            "creative arts": "9",
            "mfantse": "9",
            "religious & moral education": "9"
        },
        remarks: {
            "english language": "FAIL",
            "mathematics": "FAIL",
            "science": "FAIL",
            "social studies": "PASS",
            "arabic": "FAIL",
            "career technology": "PASS",
            "computing": "PASS",
            "creative arts": "FAIL",
            "mfantse": "FAIL",
            "religious & moral education": "FAIL"
        },
        aggregate: ""
    },
    {
        studentName: "MUSAH NASIF",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "8",
            "mathematics": "9",
            "science": "8",
            "social studies": "3",
            "arabic": "9",
            "career technology": "4",
            "computing": "3",
            "creative arts": "4",
            "mfantse": "9",
            "religious & moral education": "4"
        },
        remarks: {
            "english language": "PASS",
            "mathematics": "FAIL",
            "science": "PASS",
            "social studies": "GOOD",
            "arabic": "FAIL",
            "career technology": "GOOD",
            "computing": "GOOD",
            "creative arts": "GOOD",
            "mfantse": "FAIL",
            "religious & moral education": "GOOD"
        },
        aggregate: ""
    },
    {
        studentName: "HARUNA IBRAHIM",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "9",
            "mathematics": "9",
            "science": "9",
            "social studies": "9",
            "arabic": "9",
            "career technology": "9",
            "computing": "9",
            "creative arts": "9",
            "mfantse": "9",
            "religious & moral education": "9"
        },
        remarks: {
            "english language": "FAIL",
            "mathematics": "GOOD",
            "science": "FAIL",
            "social studies": "FAIL",
            "arabic": "FAIL",
            "career technology": "FAIL",
            "computing": "FAIL",
            "creative arts": "FAIL",
            "mfantse": "FAIL",
            "religious & moral education": "FAIL"
        },
        aggregate: ""
    },
    {
        studentName: "HAMZA USMAN",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "no data for student.": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": ""
        },
        remarks: {
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": ""
        },
        aggregate: ""
    },
    // Add more Form 1 students...
];
