const reportCards = [
    // Nursery Students
       {studentName: "ABDUL MALIK MUHAMMAD",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "2",
            "colouring": "3",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "CREDIT",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "CREDIT"},
        aggregate: "",
        position: "3rd"},
       
       {studentName: "ABDUL MUMIN ABDUBAKAR",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "2",
            "colouring": "3",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "CREDIT",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "CREDIT"},
        aggregate: "",
        position: ""},

        {studentName: "ABDUL MUMIN ABDUBAKAR",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "2",
            "colouring": "3",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "CREDIT",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "CREDIT"},
        aggregate: "",
        position: ""},

        {studentName: "ABDUL MUMIN ABDUBAKAR",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "2",
            "colouring": "3",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "CREDIT",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "CREDIT"},
        aggregate: "",
        position: ""},

        {studentName: "ABDUL MUMIN ABDUBAKAR",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "2",
            "colouring": "3",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "CREDIT",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "CREDIT"},
        aggregate: "",
        position: ""},

        {studentName: "ABDUL MUMIN ABDUBAKAR",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "2",
            "colouring": "3",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "CREDIT",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "CREDIT"},
        aggregate: "",
        position: ""},

        {studentName: "ABDUL MUMIN ABDUBAKAR",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "2",
            "colouring": "3",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "CREDIT",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "CREDIT"},
        aggregate: "",
        position: ""},

        {studentName: "ABDUL MUMIN ABDUBAKAR",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "2",
            "colouring": "3",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "CREDIT",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "CREDIT"},
        aggregate: "",
        position: ""},

        {studentName: "ABDUL MUMIN ABDUBAKAR",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "2",
            "colouring": "3",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "CREDIT",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "CREDIT"},
        aggregate: "",
        position: ""},

        {studentName: "ABDUL MUMIN ABDUBAKAR",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "2",
            "colouring": "3",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "CREDIT",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "CREDIT"},
        aggregate: "",
        position: ""},

        {studentName: "ABDUL MUMIN ABDUBAKAR",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "2",
            "colouring": "3",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "CREDIT",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "CREDIT"},
        aggregate: "",
        position: ""},

        {studentName: "ABDUL MUMIN ABDUBAKAR",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "2",
            "colouring": "3",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "CREDIT",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "CREDIT"},
        aggregate: "",
        position: ""},

        {studentName: "HIKMATU MUSTAPHA",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "3",
            "numeracy": "1",
            "writing": "4",
            "arabic": "2",
            "colouring": "3",
            "creative arts": "4"},
  remarks: {"language & literacy": "GOOD",
            "numeracy": "EXCELLENT",
            "writing": "CREDIT",
            "arabic": "VERY GOOD",
            "colouring": "GOOD",
            "creative arts": "CREDIT"},
        aggregate: "",
        position: "17th"},

        {studentName: "MOHAMMAD A. OMALITI",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "1",
            "creative arts": "1"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "EXCELLENT",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "8th"},

        {studentName: "MUHAMMAD SULAIMAN",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "2",
            "numeracy": "1",
            "writing": "3",
            "arabic": "3",
            "colouring": "4",
            "creative arts": "2"},
  remarks: {"language & literacy": "VERY GOOD",
            "numeracy": "EXCELLENT",
            "writing": "GOOD",
            "arabic": "GOOD",
            "colouring": "GOOD",
            "creative arts": "VERY GOOD"},
        aggregate: "",
        position: "14th"},

        {studentName: "SAANI ADANAN",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "1",
            "creative arts": "1"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "EXCELLENT",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "10th"},

        {studentName: "SAUDA ISMAIL",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "2",
            "numeracy": "1",
            "writing": "2",
            "arabic": "1",
            "colouring": "5",
            "creative arts": "1"},
  remarks: {"language & literacy": "VERY GOOD",
            "numeracy": "EXCELLENT",
            "writing": "VERY GOOD",
            "arabic": "EXCELLENT",
            "colouring": "CREDIT",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "13th"},

        {studentName: "SHABIWU",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "3",
            "creative arts": "1"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "GOOD",
            "creative arts": "EXCELLENT"},
        aggregate: "",
        position: "4th"},

        {studentName: "SHAMIMA MUHAMMAD",
        class: "Nursery",
        term: "Term 1",
        academicYear: "2023/2024",
   grades: {"language & literacy": "1",
            "numeracy": "1",
            "writing": "1",
            "arabic": "1",
            "colouring": "4",
            "creative arts": "2"},
  remarks: {"language & literacy": "EXCELLENT",
            "numeracy": "EXCELLENT",
            "writing": "EXCELLENT",
            "arabic": "EXCELLENT",
            "colouring": "GOOD",
            "creative arts": "VERY GOOD"},
        aggregate: "",
        position: "12th"},
    // Add more nursery students...

    // Basic 1 Students
    {
        studentName: "ABDUL-RAUF IDDRISS",
        class: "Basic 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "1",
            "history": "8",
            "mathematics": "3",
            "science": "1",
            "arabic": "4",
            "mfantse": "4",
            "religious & moral education": "1"
        },
        remarks: {
            "english language": "EXCELLENT",
            "history": "PASS",
            "mathematics": "GOOD",
            "science": "EXCELLENT",
            "arabic": "CREDIT",
            "mfantse": "CREDIT",
            "religious & moral education": "EXCELLENT"
        },
        aggregate: ""
    },
    // Add more Basic 1 students...

    // Class 4 Students
    {
        studentName: "ABDUL MAJID DONKOH",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "1",
            "history": "8",
            "mathematics": "3",
            "science": "1",
            "arabic": "4",
            "computing": "1",
            "creative arts": "9",
            "mfantse": "4",
            "religious & moral education": "1"
        },
        remarks: {
            "english language": "EXCELLENT",
            "history": "PASS",
            "mathematics": "GOOD",
            "science": "EXCELLENT",
            "arabic": "CREDIT",
            "computing": "EXCELLENT",
            "creative arts": "GOOD",
            "mfantse": "CREDIT",
            "religious & moral education": "EXCELLENT"
        },
        aggregate: ""
    },
    {
        studentName: "MASUD AL-HASSAN",
        class: "Basic 4",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "1",
            "history": "8",
            "mathematics": "3",
            "science": "1",
            "arabic": "4",
            "computing": "1",
            "creative arts": "9",
            "mfantse": "4",
            "religious & moral education": "1"
        },
        remarks: {
            "english language": "EXCELLENT",
            "history": "PASS",
            "mathematics": "GOOD",
            "science": "EXCELLENT",
            "arabic": "CREDIT",
            "computing": "EXCELLENT",
            "creative arts": "GOOD",
            "mfantse": "CREDIT",
            "religious & moral education": "EXCELLENT"
        },
        aggregate: ""
    },
    // Add more Class 4 students...

    // Form 1 Students
    {
        studentName: "IBRAHIM HALIMA",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "9",
            "mathematics": "9",
            "science": "9",
            "social studies": "8",
            "arabic": "9",
            "career technology": "9",
            "computing": "6",
            "creative arts": "8",
            "mfantse": "9",
            "religious & moral education": "9"
        },
        remarks: {
            "english language": "FAIL",
            "mathematics": "FAIL",
            "science": "FAIL",
            "social studies": "PASS",
            "arabic": "FAIL",
            "career technology": "FAIL",
            "computing": "CREDIT",
            "creative arts": "PASS",
            "mfantse": "FAIL",
            "religious & moral education": "FAIL"
        },
        aggregate: ""
    },
    {
        studentName: "AHMAB BILIKIS",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "7",
            "mathematics": "9",
            "science": "7",
            "social studies": "4",
            "arabic": "9",
            "career technology": "6",
            "computing": "2",
            "creative arts": "5",
            "mfantse": "9",
            "religious & moral education": "5"
        },
        remarks: {
            "english language": "PASS",
            "mathematics": "FAIL",
            "science": "PASS",
            "social studies": "GOOD",
            "arabic": "FAIL",
            "career technology": "CREDIT",
            "computing": "VERY GOOD",
            "creative arts": "FAIL",
            "mfantse": "FAIL",
            "religious & moral education": "CREDIT"
        },
        aggregate: ""
    },
    {
        studentName: "APPIAH HANIFA",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "8",
            "mathematics": "9",
            "science": "9",
            "social studies": "5",
            "arabic": "9",
            "career technology": "4",
            "computing": "3",
            "creative arts": "4",
            "mfantse": "9",
            "religious & moral education": "4"
        },
        remarks: {
            "english language": "PASS",
            "mathematics": "FAIL",
            "science": "FAIL",
            "social studies": "CREDIT",
            "arabic": "FAIL",
            "career technology": "GOOD",
            "computing": "GOOD",
            "creative arts": "GOOD",
            "mfantse": "FAIL",
            "religious & moral education": "GOOD"
        },
        aggregate: ""
    },
    {
        studentName: "ABDUL MUMIN BASIRA",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "6",
            "mathematics": "9",
            "science": "6",
            "social studies": "1",
            "arabic": "9",
            "career technology": "4",
            "computing": "3",
            "creative arts": "4",
            "mfantse": "9",
            "religious & moral education": "4"
        },
        remarks: {
            "english language": "CREDIT",
            "mathematics": "FAIL",
            "science": "CREDIT",
            "social studies": "EXCELLENT",
            "arabic": "FAIL",
            "career technology": "GOOD",
            "computing": "GOOD",
            "creative arts": "GOOD",
            "mfantse": "FAIL",
            "religious & moral education": "GOOD"
        },
        aggregate: ""
    },
    {
        studentName: "MOHAMMAD IBRAHIM",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "9",
            "mathematics": "9",
            "science": "9",
            "social studies": "7",
            "arabic": "9",
            "career technology": "7",
            "computing": "7",
            "creative arts": "9",
            "mfantse": "9",
            "religious & moral education": "9"
        },
        remarks: {
            "english language": "FAIL",
            "mathematics": "FAIL",
            "science": "FAIL",
            "social studies": "PASS",
            "arabic": "FAIL",
            "career technology": "PASS",
            "computing": "PASS",
            "creative arts": "FAIL",
            "mfantse": "FAIL",
            "religious & moral education": "FAIL"
        },
        aggregate: ""
    },
    {
        studentName: "MUSAH NASIF",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "8",
            "mathematics": "9",
            "science": "8",
            "social studies": "3",
            "arabic": "9",
            "career technology": "4",
            "computing": "3",
            "creative arts": "4",
            "mfantse": "9",
            "religious & moral education": "4"
        },
        remarks: {
            "english language": "PASS",
            "mathematics": "FAIL",
            "science": "PASS",
            "social studies": "GOOD",
            "arabic": "FAIL",
            "career technology": "GOOD",
            "computing": "GOOD",
            "creative arts": "GOOD",
            "mfantse": "FAIL",
            "religious & moral education": "GOOD"
        },
        aggregate: ""
    },
    {
        studentName: "HARUNA IBRAHIM",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "english language": "9",
            "mathematics": "9",
            "science": "9",
            "social studies": "9",
            "arabic": "9",
            "career technology": "9",
            "computing": "9",
            "creative arts": "9",
            "mfantse": "9",
            "religious & moral education": "9"
        },
        remarks: {
            "english language": "FAIL",
            "mathematics": "GOOD",
            "science": "FAIL",
            "social studies": "FAIL",
            "arabic": "FAIL",
            "career technology": "FAIL",
            "computing": "FAIL",
            "creative arts": "FAIL",
            "mfantse": "FAIL",
            "religious & moral education": "FAIL"
        },
        aggregate: ""
    },
    {
        studentName: "HAMZA USMAN",
        class: "Form 1",
        term: "Term 1",
        academicYear: "2023/2024",
        grades: {
            "no data for student.": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": ""
        },
        remarks: {
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": "",
            "": ""
        },
        aggregate: ""
    },
    // Add more Form 1 students...
];
